### PR TITLE
chore: secure github actions using hash instead of versions

### PR DESCRIPTION
**Pull request by jeromevdl**
**Issue #, if available:**

## Description of changes:

Replace all explicit versions with hashes to pin to a specific version.

**Checklist**

 

* [x] [Meet tenets criteria](https://docs.powertools.aws.dev/lambda-java/#tenets)
* [ ] Update tests
* [ ] Update docs
* [x] PR title follows [conventional commit semantics](https://www.conventionalcommits.org/en/v1.0.0/)

## Breaking change checklist

**RFC issue #**:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by scottgerring — COMMENTED** [review]
I think this is an improvement on how it is today and we should merge it.

I also think in a subsequent task it is worth digging into the smaller 3rd party actions - e.g. `ahmadnassri/action-workflow-run-wait`, `release-drafter/release-drafter`, and `jacobtomlinson/gha-find-replace` and checking if we can't get away with some github 1st party action, _or_, a powertools shared action, _or_ failing the previous options reviewing the code of the thing.

**Review by scottgerring — APPROVED** [review]

**Comment by scottgerring** [comment]
@jeromevdl I think we should merge this - wdyt?

**Comment by jeromevdl** [comment]
agree!

**Comment by jeromevdl** [comment]
except that build fails without clear reason why...

**Comment by jeromevdl** [comment]
> except that build fails without clear reason why...

It was because of the docs.yaml deleted by @kozub, the merge didn't work well... I've deleted it.

**Review by sthulb — APPROVED** [review]
This can be merged assuming the code at each of the hashes has been reviewed to be safe.

**Pull request merged**
