### PR TITLE
chore: Reporting size of the jars in GitHub comments

### PR DESCRIPTION
**Pull request by jeromevdl**
**Issue #, if available:** #1102 

## Description of changes:

Display a report in GitHub comments about jars size. (Ideally would be great to have the history and see if it's growing)

**Checklist**

 

* [x] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-java/#tenets)
* [ ] Update tests
* [ ] Update docs
* [x] PR title follows [conventional commit semantics](https://www.conventionalcommits.org/en/v1.0.0/)

## Breaking change checklist

**RFC issue #**:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jeromevdl** [comment]
Help: How can we compare with previous versions of each artifact? (ideally from maven central or any other way)

**Comment by scottgerring** [comment]
Hey @jeromevdl can we help here ?!

**Comment by jeromevdl** [comment]
@scottgerring Yes, for the moment I report the size of the built artifacts. Ideally I'd like to compare with the current release to see if it grows or not, but not sure how to achieve this...

**Comment by jeromevdl** [comment]
My idea for the comparison with previous versions:
- During release, generate a json file containing the artifacts size that we push to S3 (public access allowed on the S3 file).
- Then when there is a PR, we retrieve the json file to be able to compare.

We'll do that when refactoring the release process... We can already merge the report itself.

Ready for review!

**Comment by scottgerring** [comment]
Can we do this with [sonar custom metrics](https://docs.sonarsource.com/sonarqube/8.9/instance-administration/custom-measures/)?

**Comment by jeromevdl** [comment]
Will push that initial version without comparison with previous versions.
Actually it would be great to have a report of the new dependencies added... or a dependency tree or something to see if add weight to the final asset the user will deploy.

**Pull request merged**
