### PR TITLE
fix(v2): Add default transformation manager in params module

### PR DESCRIPTION
**Pull request by ritigupt**
**Issue #, if available:**
[issue](https://github.com/aws-powertools/powertools-lambda-java/issues/1544)
## Description of changes:
Added default transformation Manager in ssm and secrets builder 

**Checklist**

 

* [ ] [Meet tenets criteria](https://docs.powertools.aws.dev/lambda-java/#tenets)
* [ ] Update tests
* [ ] Update docs
* [x] PR title follows [conventional commit semantics](https://www.conventionalcommits.org/en/v1.0.0/)

## Breaking change checklist

**RFC issue #**:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by jeromevdl — COMMENTED** [review]
Why is it not done in DynamoDB and AppConfig ?

**Comment by ritigupt** [comment]
> Why is it not done in DynamoDB and AppConfig ?
done.

**Comment by scottgerring** [comment]
Hey @ritigupt thanks for the changes! 
I'd love to see some tests covering this, as we only picked up the issue as part of manually deploying and running the examples - this could be as simple as creating the parameter provider and trying to use a transformer. What do you think?

**Comment by ritigupt** [comment]
> Hey @ritigupt thanks for the changes! I'd love to see some tests covering this, as we only picked up the issue as part of manually deploying and running the examples - this could be as simple as creating the parameter provider and trying to use a transformer. What do you think?

Agreed. Will add Unit tests covering these in a while.

**Comment by ritigupt** [comment]
@scottgerring I think I messed up something in this branch while trying to sync up this branch with my forked repo. I have opened another PR [#1549 ](https://github.com/aws-powertools/powertools-lambda-java/pull/1549), please ignore this one.

**Comment by ritigupt** [comment]
@scottgerring I think I messed up something in this branch while trying to sync up this branch with my forked repo. I have opened another PR https://github.com/aws-powertools/powertools-lambda-java/pull/1549, please ignore this one.

**Pull request closed without merging**
