### PR TITLE
test: Roll SLF4J log4j bindings to v2

### PR DESCRIPTION
**Pull request by scottgerring**
**Issue #, if available:** #1180

## Description of changes:
We generally couple directly against Log4j, but [in a couple of places](https://github.com/search?q=repo%3Aawslabs%2Faws-lambda-powertools-java+%22import+org.slf4j%22&type=code) we write to the slf4j API, which is then adapted back to log4j by log4j's `log4j-slf4j-impl` package:

https://github.com/awslabs/aws-lambda-powertools-java/blob/76ca20f2df7631b6cf4eaed852a55ab95f27be1d/powertools-serialization/pom.xml#L52-L55

Because this adapter is being pulled in by our code and is using slf4j-v1, customers using slf4j-v2 themselves can have issues using the powertools (see #1180). This PR switches the adapter to slf4j-v2. 

Long term we intend to switch to slf4j (#995, #965), rather than coupling directly against log4j. As this will be a breaking change, it has been earmarked for powertools for java v2. 

**Checklist**

 

* [ ] [Meet tenets criteria](https://awslabs.github.io/aws-lambda-powertools-java/#tenets)
* [ ] Update tests
* [ ] Update docs
* [ ] PR title follows [conventional commit semantics](https://www.conventionalcommits.org/en/v1.0.0/)

## Breaking change checklist

**RFC issue #**:

* [ ] Migration process documented
* [ ] Implement warnings (if it can live side by side)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by scottgerring** [comment]
@jeromevdl what do you think? This seems pretty harmless to me, and the [slf4j upgrade-to-v2 FAQ](https://www.slf4j.org/faq.html#changesInVersion200) lists it as a non-breaking change. 

I have also tried to document explicitly on this PR the state of logging in the repo and our long term plans here.

**Review by jeromevdl — COMMENTED** [review]
Looks ok.

That's all the slf4j reference we have ?

**Comment by scottgerring** [comment]
> Looks ok.
> 
> That's all the slf4j reference we have ? I still don't understand why we introduced slf4j here...
> 
> @msailes any reason for this; Was it to fix a warning in the log: #123 ?

You can see [that some of our code](https://github.com/search?q=repo%3Aawslabs%2Faws-lambda-powertools-java+%22import+org.slf4j%22&type=code) couples against it instead of log4j. I don't know if it was initially an autocomplete accident or good intentions ("we should be using slf4j not log4j").

**Comment by jeromevdl** [comment]
@scottgerring anything else to do on this one? it is marked as draft...

**Review by jeromevdl — APPROVED** [review]

**Pull request merged**
